//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBD.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HBD.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL;AFN;ARS;AWG;AUD;AZN;BSD;BBD;BYR;BZD;BMD;BOB;BAM;BWP;BGN;BRL;BND;KHR;CAD;KYD;CLP;CNY;COP;CRC;HRK;CUP;CZK;DKK;DOP;XCD;EGP;SVC;EEK;EUR;FKP;FJD;GHC;GIP;GTQ;GGP;GYD;HNL;HKD;HUF;ISK;INR;IDR;IRR;IMP;ILS;JMD;JPY;JEP;KZT;KPW;KRW;KGS;LAK;LVL;LBP;LRD;LTL;MKD;MYR;MUR;MXN;MNT;MZN;NAD;NPR;ANG;NZD;NIO;NGN;NOK;OMR;PKR;PAB;PYG;PEN;PHP;PLN;QAR;RON;RUB;SHP;SAR;RSD;SCR;SGD;SBD;SOS;ZAR;LKR;SEK;CHF;SRD;SYP;TWD;THB;TTD;TRL;TVD;UAH;GBP;USD;UYU;UZS;VEF;VND;YER;ZWD.
        /// </summary>
        internal static string CultureInfoHelper_CurrencyCharacters {
            get {
                return ResourceManager.GetString("CultureInfoHelper_CurrencyCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $;ƒ;¥;₡;₱;£;€;¢;₩;₭;₨;₮;₦;฿;₤;₴;₫.
        /// </summary>
        internal static string CultureInfoHelper_CurrencySymbols {
            get {
                return ResourceManager.GetString("CultureInfoHelper_CurrencySymbols", resourceCulture);
            }
        }
    }
}
